### PR TITLE
Fix: search 0 failed.

### LINKED ISSUE #3904: [BUG] can not search equals 0
## Version information

 - Laravel: v5.7.19
 - Voyager: v1.1.11
 - PHP: 7.2.10
 - Database: MySQL 5.7.24

## Description

search one column equals 0, failed.

## Steps To Reproduce
1. run `php artisan voyager:install --with-dummy`
2. open local voyager web [/admin/posts](http://laravel-demo.localhost/admin/posts)
3. edit some posts, change "Featured" to 1 
4. search by equals 1, it's fine. URL: [/admin/posts?key=featured&filter=equals&s=1](http://laravel-demo.localhost/admin/posts?key=featured&filter=equals&s=1)
5. search by equals 0, failed. URL: [/admin/posts?key=featured&filter=equals&s=0](http://laravel-demo.localhost/admin/posts?key=featured&filter=equals&s=0)

## Expected behavior
search by equals 0, should return posts which featured=0

## Screenshots
image
image
image

### PR DESCRIPTION
**Pull request by shaunthegeek**
Fixes #3904

### CODE REVIEW

File: src/Http/Controllers/VoyagerBaseController.php [hunk 1]
```diff
@@ -65,7 +65,7 @@ public function index(Request $request)
             // If a column has a relationship associated with it, we do not want to show that field
             $this->removeRelationshipField($dataType, 'browse');
 
-            if ($search->value && $search->key && $search->filter) {
+            if ((!empty($search->value) || $search->value === '0') && $search->key && $search->filter) {
```
Comment (emptynick) [inline src/Http/Controllers/VoyagerBaseController.php]: This will result in the same and is much more generic
```suggestion
            if ($search->value != '' && $search->key && $search->filter) {
```

**Review by emptynick — DISMISSED** [review]

**Comment by shaunthegeek** [comment]
is anybody there? @emptynick

**Review by fletch3555 — APPROVED** [review]

**Comment by fletch3555** [comment]
Patience @sinkcup.  We'll get to it when we get to it.
